# Generated by Django 4.1.2 on 2023-10-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Enfermer@', 'Enfermer@'), ('Médico General', 'Médico General')], default='Cardiologist', max_length=50),
        ),
    ]
